packages:
  - apps/*
  - packages/*

catalog:
  "@effect/platform-node": 4.0.0-beta.107
  "@types/node": 24.13.3
  effect: 4.0.0-beta.107
  rolldown: 1.2.5
  typescript: 7.0.2
  vitest: 4.1.11

allowBuilds:
  msgpackr-extract: false

minimumReleaseAgeExclude:
  - "@effect/openapi-generator@4.0.0-beta.107"
  - "@effect/platform-node-shared@4.0.0-beta.107"
  - "@effect/platform-node@4.0.0-beta.107"
  - effect@4.0.0-beta.107
  - "@effect/tsgo-darwin-arm64@0.36.5"
  - "@effect/tsgo-darwin-x64@0.36.5"
  - "@effect/tsgo-linux-arm64@0.36.5"
  - "@effect/tsgo-linux-arm@0.36.5"
  - "@effect/tsgo-linux-x64@0.36.5"
  - "@effect/tsgo-win32-arm64@0.36.5"
  - "@effect/tsgo-win32-x64@0.36.5"
  - "@effect/tsgo@0.36.5"
