packages:
  - apps/*
  - packages/*

catalog:
  "@effect/platform-node": 4.0.0-beta.101
  "@types/node": 24.10.14
  effect: 4.0.0-beta.101
  rolldown: 1.2.0
  typescript: 7.0.2
  vitest: 4.1.10

allowBuilds:
  msgpackr-extract: false

minimumReleaseAgeExclude:
  - "@effect/openapi-generator@4.0.0-beta.101"
  - "@effect/platform-node-shared@4.0.0-beta.101"
  - "@effect/platform-node@4.0.0-beta.101"
  - effect@4.0.0-beta.101
