import { camelize } from "@effect/openapi-generator/Utils"
import { Predicate } from "effect"
import * as String from "effect/String"
import type {
  OpenAPISpec,
  OpenAPISpecMethodName,
  OpenAPISpecOperation,
} from "effect/unstable/httpapi/OpenApi"
import { routeOperation } from "./cli-routes.ts"

export interface CliSourceDocument {
  readonly document: OpenAPISpec
  readonly family: "distributor" | "investor" | "public"
}

export interface GeneratedCliFile {
  readonly content: string
  readonly path: string
}

const methods: ReadonlyArray<OpenAPISpecMethodName> = [
  "delete",
  "get",
  "head",
  "options",
  "patch",
  "post",
  "put",
  "trace",
]

const operationDescription = (operation: OpenAPISpecOperation): string =>
  operation.description ?? operation.summary ?? operation.operationId

const resourceName = (operation: OpenAPISpecOperation): string =>
  String.kebabCase(operation.tags[0].replace(/\s*\([^)]*\)\s*/g, " "))

const findOperation = (
  document: OpenAPISpec,
  operationId: string,
): {
  readonly method: OpenAPISpecMethodName
  readonly operation: OpenAPISpecOperation
  readonly path: string
} => {
  for (const [path, item] of Object.entries(document.paths)) {
    for (const method of methods) {
      const operation = item[method]
      if (operation?.operationId === operationId) {
        return { method, operation, path }
      }
    }
  }

  throw new Error(`OpenAPI operation "${operationId}" was not found`)
}

const schemaFormat = (schema: object): string | undefined =>
  Predicate.hasProperty(schema, "format") && Predicate.isString(schema.format)
    ? schema.format
    : undefined

const renderPublicGetFund = (document: OpenAPISpec): string => {
  const { method, operation, path } = findOperation(document, "Get Fund")
  const parameters = operation.parameters
  if (parameters.length !== 1) {
    throw new Error(`Get Fund must declare exactly one parameter; found ${parameters.length}`)
  }

  const parameter = parameters[0]
  if (
    parameter === undefined ||
    parameter.in !== "path" ||
    parameter.name !== "fundId" ||
    !parameter.required ||
    schemaFormat(parameter.schema) !== "uuid"
  ) {
    throw new Error("Get Fund must declare one required UUID path parameter named fundId")
  }

  const resource = resourceName(operation)
  const route = routeOperation({
    method: method.toUpperCase(),
    path,
    resource,
  })
  const description = operationDescription(operation)
  const definition = {
    action: route.action,
    description,
    family: "public",
    method: method.toUpperCase(),
    operationId: operation.operationId,
    parameters: [
      {
        description: parameter.description ?? parameter.name,
        flag: String.kebabCase(parameter.name),
        in: parameter.in,
        name: parameter.name,
        required: parameter.required,
        schema: parameter.schema,
      },
    ],
    path,
    requestBody: null,
    resource: route.resource,
    safety: "read",
  }

  const definitionSource = JSON.stringify(definition, null, 2).replaceAll("\n", "\n  ")

  return `// This file is generated by tools/generate-clients.ts. Do not edit it by hand.

import { PublicApi } from "@spiko/public-api-client"
import { Effect, Schema } from "effect"
import { Flag } from "effect/unstable/cli"
import { defineOperation } from "../cli.ts"

export const GetFund = defineOperation({
  definition: ${definitionSource},
  parameters: {
    fundId: Flag.string("${String.kebabCase(parameter.name)}").pipe(
      Flag.withSchema(Schema.String.check(Schema.isUUID())),
      Flag.withMetavar("UUID"),
      Flag.withDescription(${JSON.stringify(`Required path parameter: ${parameter.name} — ${parameter.description ?? parameter.name}`)}),
    ),
  },
  invoke: ({ fundId }) => Effect.flatMap(PublicApi, (client) => client.${camelize(operation.operationId)}(fundId, undefined)),
})

export const PublicOperations = [GetFund] as const
`
}

export const generateCliFiles = (
  documents: ReadonlyArray<CliSourceDocument>,
): ReadonlyArray<GeneratedCliFile> => {
  const publicDocument = documents.find((source) => source.family === "public")
  if (publicDocument === undefined) {
    throw new Error("The Public OpenAPI document is required to generate the CLI")
  }

  return [
    {
      content: renderPublicGetFund(publicDocument.document),
      path: "apps/cli/src/generated/public.ts",
    },
  ]
}
