#!/usr/bin/env node

import * as OpenApiGenerator from "@effect/openapi-generator/OpenApiGenerator"
import { camelize } from "@effect/openapi-generator/Utils"
import * as NodeHttpClient from "@effect/platform-node/NodeHttpClient"
import * as NodeRuntime from "@effect/platform-node/NodeRuntime"
import * as NodeServices from "@effect/platform-node/NodeServices"
import { Cause, Console, Effect, FileSystem, Schema } from "effect"
import { Command, Flag } from "effect/unstable/cli"
import * as HttpClient from "effect/unstable/http/HttpClient"
import type { OpenAPISpec, OpenAPISpecMethodName } from "effect/unstable/httpapi/OpenApi"

const apis = [
  {
    id: "public",
    clientName: "SpikoPublicApi",
    generatedFile: "packages/public-api-client/src/generated.ts",
    specFile: "openapi/public-api.json",
    specUrl: "https://public-api.spiko.io/v0/docs/openapi.json",
  },
  {
    id: "investor",
    clientName: "SpikoInvestorApi",
    generatedFile: "packages/investor-api-client/src/generated.ts",
    specFile: "openapi/investor-api.json",
    specUrl: "https://investor-api.spiko.io/v1/docs/openapi.json",
  },
  {
    id: "distributor",
    clientName: "SpikoDistributorApi",
    generatedFile: "packages/distributor-api-client/src/generated.ts",
    specFile: "openapi/distributor-api.json",
    specUrl: "https://distributor-api.spiko.io/v0/docs/openapi.json",
  },
] as const

type ApiDefinition = (typeof apis)[number]

const parseJson = Schema.decodeUnknownEffect(Schema.fromJsonString(Schema.Json))

const methods: ReadonlyArray<OpenAPISpecMethodName> = [
  "delete",
  "get",
  "head",
  "options",
  "patch",
  "post",
  "put",
  "trace",
]

const readSpec = (definition: ApiDefinition, fetch: boolean) =>
  Effect.gen(function* () {
    const fs = yield* FileSystem.FileSystem

    if (!fetch) {
      return yield* fs.readFileString(definition.specFile)
    }

    const httpClient = (yield* HttpClient.HttpClient).pipe(HttpClient.filterStatusOk)
    const response = yield* httpClient.get(definition.specUrl)
    const body = yield* response.text
    const parsed = yield* parseJson(body)
    const normalized = `${JSON.stringify(parsed, null, 2)}\n`

    yield* fs.writeFileString(definition.specFile, normalized)
    yield* Console.log(`Updated ${definition.specFile}`)

    return normalized
  })

const generateCatalog = (
  documents: ReadonlyArray<readonly [ApiDefinition, OpenAPISpec]>,
): string => {
  const catalog = Object.fromEntries(
    documents.map(([definition, document]) => {
      const operations: Record<string, unknown> = {}

      for (const [path, pathItem] of Object.entries(document.paths)) {
        for (const method of methods) {
          const operation = pathItem[method]
          if (operation === undefined) {
            continue
          }

          const operationId = operation.operationId

          operations[camelize(operationId)] = {
            description: operation.description ?? operation.summary ?? operationId,
            method: method.toUpperCase(),
            parameters: operation.parameters.map((parameter) => ({
              in: parameter.in,
              name: parameter.name,
              required: parameter.required,
            })),
            path,
            requestBody: operation.requestBody === undefined ? undefined : { required: true },
          }
        }
      }

      return [definition.id, operations]
    }),
  )

  return `// This file is generated by tools/generate-clients.ts. Do not edit it by hand.

export const ApiNames = ["public", "investor", "distributor"] as const

export type ApiName = (typeof ApiNames)[number]

export interface OperationParameter {
  readonly in: "query" | "header" | "path" | "cookie"
  readonly name: string
  readonly required: boolean
}

export interface OperationMetadata {
  readonly description: string
  readonly method: string
  readonly parameters: ReadonlyArray<OperationParameter>
  readonly path: string
  readonly requestBody?: {
    readonly required: boolean
  }
}

export const OperationCatalog = ${JSON.stringify(catalog, null, 2)} as const satisfies Readonly<
  Record<ApiName, Readonly<Record<string, OperationMetadata>>>
>
`
}

const fetch = Flag.boolean("fetch").pipe(
  Flag.withDescription("Download the latest Spiko specifications before generating clients"),
)

const generate = Command.make("generate-clients", { fetch }, ({ fetch }) =>
  Effect.gen(function* () {
    const fs = yield* FileSystem.FileSystem
    const generator = yield* OpenApiGenerator.OpenApiGenerator

    yield* fs.makeDirectory("openapi", { recursive: true })

    const documents = yield* Effect.forEach(apis, (definition) =>
      Effect.gen(function* () {
        const source = yield* readSpec(definition, fetch)
        const json = yield* parseJson(source)
        // The generator's own CLI uses this boundary cast: it accepts external OpenAPI
        // documents but does not currently export a runtime Schema for OpenAPISpec.
        const spec = json as unknown as OpenAPISpec
        const warnings: Array<OpenApiGenerator.OpenApiGeneratorWarning> = []
        const generated = yield* generator.generate(spec, {
          format: "httpclient",
          name: definition.clientName,
          onWarning: (warning) => {
            warnings.push(warning)
          },
        })

        yield* fs.makeDirectory(
          definition.generatedFile.slice(0, definition.generatedFile.lastIndexOf("/")),
          {
            recursive: true,
          },
        )
        yield* fs.writeFileString(
          definition.generatedFile,
          `// This file is generated by tools/generate-clients.ts. Do not edit it by hand.\n\n${generated}`
            .replace(/[ \t]+$/gm, "")
            .trimEnd() + "\n",
        )

        for (const warning of warnings) {
          yield* Console.error(
            `WARNING [${warning.code}] ${warning.method?.toUpperCase() ?? ""} ${warning.path ?? ""}: ${warning.message}`,
          )
        }

        yield* Console.log(`Generated ${definition.generatedFile}`)
        return [definition, spec] as const
      }),
    )

    const catalogFile = "apps/cli/src/generated/operations.ts"
    yield* fs.makeDirectory("apps/cli/src/generated", { recursive: true })
    yield* fs.writeFileString(catalogFile, generateCatalog(documents))
    yield* Console.log(`Generated ${catalogFile}`)
  }),
)

Command.run(generate, { version: "0.1.0" }).pipe(
  Effect.provide(OpenApiGenerator.layerTransformerSchema),
  Effect.provide(NodeHttpClient.layerUndici),
  Effect.tapCause((cause) => Console.error(Cause.pretty(cause))),
  Effect.provide(NodeServices.layer),
  NodeRuntime.runMain,
)
